### ISSUE TITLE
How to test the model with multi-GPU?

### ISSUE THREAD

**Issue by lewisyangliu** [thstkdgus35/EDSR-PyTorch#30]
Thank you for your excellent code.

I encounter a problem when I train this code. As the code wrote in 'main.py': 

while not t.terminate():
        t.train()
        t.test()

where we can see that the test phase begins immediately after the train phase. However, since the GPU memory is not released, and the test model only runs on a single GPU even though this model can run on 4 GPUs on the train phase. The problem of out of memory occurs then.

Actually, I can run this code successfully on 4 GPUs of GTX 1080Ti, even though the test model only runs on a single GPU. In recent days my work environment changes and I train these netwoks on 4 GPUs of Titan Xp. Although the GPU memory increases the problem of out of memory occurs.

I wonder if we can test the model with multi-GPU just like the train phase. By the way, setting --chop_forward doesn't work for me.

Thank you!

**Comment by thstkdgus35** [comment]
Hello.

Multi-GPU evaluation problem is not related to the memory release you mentioned.

It just happens because the test batch-size is always 1, so only a single GPU takes the batch.

However, our [forward_chop function](https://github.com/thstkdgus35/EDSR-PyTorch/blob/984b35d9d6832213db1f9be76bdd77976a9866ef/code/model/__init__.py#L114-L153) is implemented to utilize multiple GPUs.

Since --chop_forward argument is renamed to --chop, you can use multiple GPUs in evaluation stage with --n_GPUs 4 --chop arguments.

Thank you!

**Comment by lewisyangliu** [comment]
It works now, thanks!
